version: '3.9'
services:

  blood_pressure:
      build: .
      container_name: blood_pressure
      ports:
        - "5005:5005"
      restart: unless-stopped
      volumes:
        - /home/ravenstudios/flask_blood_pressure/instance:/app/instance
